version: '3'
services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'ostech'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ostech-mysql:/var/lib/mysql

volumes:
  ostech-mysql: